# basicConfig.properties

resourcePrefix = "D:\\Lowcode-ontology-generator\\Lowcode-ontology-generator-backend\\backend\\src\\main\\resources\\multi-source\\"
templatePrefix = "D:\\Lowcode-ontology-generator\\Lowcode-ontology-generator-backend\\backend\\src\\main\\resources\\templates\\BigCQ_dataset\\"
serializeFilePath = "D:\\"
targetOntologyPath = "D:\cybersecurityOntologies\\"